---
title: "Integration robustness"
author: Alonso Ortega-Gurrola
date: | 
      | Started on 06/07/2022
      | Compiled: `r format(Sys.Date(), "%B %d, %Y")`
output:
  html_document:
    df_print: paged
    toc: yes
    toc_float: no
  github_document:
    toc: yes
  html_notebook:
    df_print: paged
    highlight: tango
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
editor_options:
  chunk_output_type: inline
always_allow_html: yes
---

# Installing required packages

```{r eval = FALSE, warning=FALSE, message=FALSE}
library(remotes)
remotes::install_github("davidsjoberg/ggsankey")
```

# Libraries

```{r warning=FALSE, message=FALSE}
library(Seurat)
library(sctransform)
library(gridExtra)
library(dplyr)
library(tximport)
library(Matrix)
library(ggplot2)
library(stringr)
library(SeuratWrappers)
library(dendextend)
library(dynamicTreeCut)
library(tibble)
library(ggsankey)
```

# Reading Seurat objects

```{r}
r18.500g.80dim <- readRDS("R18_220603_CCA_integration_reptiles_Dims80_features_500.RDS")
r18.1000g.80dim <- readRDS("R18_220523_CCA_integration_reptiles_Dims80_features_1000.RDS")
r18.2000g.80dim <- readRDS("R18_220603_CCA_integration_reptiles_Dims80_features_2000.RDS")
r18.3000g.80dim <- readRDS("R18_220603_CCA_integration_reptiles_Dims80_features_3000.RDS")
```

```{r}
r18.1000g.50dim <- readRDS("R18_220603_CCA_integration_reptiles_Dims50_features_1000.RDS")
r18.1000g.80dim <- readRDS("R18_220523_CCA_integration_reptiles_Dims80_features_1000.RDS")
r18.1000g.120dim <- readRDS("R18_220603_CCA_integration_reptiles_Dims120_features_1000.RDS")
r18.1000g.150dim <- readRDS("R18_220603_CCA_integration_reptiles_Dims150_features_1000.RDS")
r18.1000g.200dim <- readRDS("R18_220603_CCA_integration_reptiles_Dims200_features_1000.RDS")
```

# Bringing all to same resolution 

```{r}
r18.500g.80dim <- FindClusters(r18.500g.80dim, resolution = 2.1, verbose = FALSE, algorithm = 3)
r18.1000g.80dim <- FindClusters(r18.1000g.80dim, resolution = 2.1, verbose = FALSE, algorithm = 3)
r18.2000g.80dim <- FindClusters(r18.2000g.80dim, resolution = 2.1, verbose = FALSE, algorithm = 3)
r18.3000g.80dim <- FindClusters(r18.3000g.80dim, resolution = 2.1, verbose = FALSE, algorithm = 3)

# renaming clusters starting from 1
new.ids <- seq(1, length(levels(Idents(r18.500g.80dim))), by=1)
names(new.ids) <- levels(Idents(r18.500g.80dim))
r18.500g.80dim <- RenameIdents(r18.500g.80dim, new.ids)

new.ids <- seq(1, length(levels(Idents(r18.1000g.80dim))), by=1)
names(new.ids) <- levels(Idents(r18.1000g.80dim))
r18.1000g.80dim <- RenameIdents(r18.1000g.80dim, new.ids)

new.ids <- seq(1, length(levels(Idents(r18.2000g.80dim))), by=1)
names(new.ids) <- levels(Idents(r18.2000g.80dim))
r18.2000g.80dim <- RenameIdents(r18.2000g.80dim, new.ids)

new.ids <- seq(1, length(levels(Idents(r18.3000g.80dim))), by=1)
names(new.ids) <- levels(Idents(r18.3000g.80dim))
r18.3000g.80dim <- RenameIdents(r18.3000g.80dim, new.ids)

# stash new clusters into a metadata column
r18.500g.80dim[["SLM_identities_res2.1"]] <- Idents(r18.500g.80dim)
r18.1000g.80dim[["SLM_identities_res2.1"]] <- Idents(r18.1000g.80dim)
r18.2000g.80dim[["SLM_identities_res2.1"]] <- Idents(r18.2000g.80dim)
r18.3000g.80dim[["SLM_identities_res2.1"]] <- Idents(r18.3000g.80dim)
```

# Creating df for Sankey plot

```{r}
# grab cell names and Ident
r18.500g.80dim.cells <- colnames(r18.500g.80dim)
r18.500g.80dim.clusters <- as.character(Idents(r18.500g.80dim))
r18.500g.80dim.df <- cbind(r18.500g.80dim.clusters, r18.500g.80dim.cells)
rep.tree <- readRDS("Tree_3Sp_500g80dim_220527_Spea_algo3_res2.1.rds")
speciesTree.order.1 <- labels(rep.tree)
r18.500g.80dim.df <- r18.500g.80dim.df[order(match(r18.500g.80dim.df[,1], speciesTree.order.1)),]
r18.500g.80dim.df <- as.data.frame(r18.500g.80dim.df)

r18.1000g.80dim.cells <- colnames(r18.1000g.80dim)
r18.1000g.80dim.clusters <- as.character(Idents(r18.1000g.80dim))
r18.1000g.80dim.df <- cbind(r18.1000g.80dim.clusters, r18.1000g.80dim.cells)
rep.tree <- readRDS("Tree_R18_220525_Spea_algo3_res2.1.rds")
speciesTree.order.2 <- labels(rep.tree)
r18.1000g.80dim.df <- r18.1000g.80dim.df[order(match(r18.1000g.80dim.df[,1], speciesTree.order.2)),]
r18.1000g.80dim.df <- as.data.frame(r18.1000g.80dim.df)

r18.2000g.80dim.cells <- colnames(r18.2000g.80dim)
r18.2000g.80dim.clusters <- as.character(Idents(r18.2000g.80dim))
r18.2000g.80dim.df <- cbind(r18.2000g.80dim.clusters, r18.2000g.80dim.cells)
rep.tree <- readRDS("R18_tree_rotated_final.rds")
speciesTree.order.3 <- labels(rep.tree)
r18.2000g.80dim.df <- r18.2000g.80dim.df[order(match(r18.2000g.80dim.df[,1], speciesTree.order.3)),]
r18.2000g.80dim.df <- as.data.frame(r18.2000g.80dim.df)

r18.3000g.80dim.cells <- colnames(r18.3000g.80dim)
r18.3000g.80dim.clusters <- as.character(Idents(r18.3000g.80dim))
r18.3000g.80dim.df <- cbind(r18.3000g.80dim.clusters, r18.3000g.80dim.cells)
rep.tree <- readRDS("Tree_3Sp_3000g80dim_220527_Spea_algo3_res2.1.rds")
speciesTree.order.4 <- labels(rep.tree)
r18.3000g.80dim.df <- r18.3000g.80dim.df[order(match(r18.3000g.80dim.df[,1], speciesTree.order.4)),]
r18.3000g.80dim.df <- as.data.frame(r18.3000g.80dim.df)
```

# Generating Sankey plot lists

```{r fig.height=10, fig.width=10}
mat.r18.500g <- matrix(nrow = length(speciesTree.order.1), ncol = 2)
mat.r18.500g <- as.data.frame(mat.r18.500g)
mat.r18.500g$V1 <- speciesTree.order.1
a <- 1
for(i in 1:length(speciesTree.order.1)) {
  b <- speciesTree.order.1[a]
  cell.names <- r18.500g.80dim.df$r18.500g.80dim.cells[r18.500g.80dim.df$r18.500g.80dim.clusters==b]
  cell.names <- paste(cell.names, collapse = ", ")
  mat.r18.500g[i,2] <- cell.names
  a <- a + 1
}

mat.r18.1000g <- matrix(nrow = length(speciesTree.order.2), ncol = 2)
mat.r18.1000g <- as.data.frame(mat.r18.1000g)
mat.r18.1000g$V1 <- speciesTree.order.2
a <- 1
for(i in 1:length(speciesTree.order.2)) {
  b <- speciesTree.order.2[a]
  cell.names <- r18.1000g.80dim.df$r18.1000g.80dim.cells[r18.1000g.80dim.df$r18.1000g.80dim.clusters==b]
  cell.names <- paste(cell.names, collapse = ", ")
  mat.r18.1000g[i,2] <- cell.names
  a <- a + 1
}

mat.r18.2000g <- matrix(nrow = length(speciesTree.order.3), ncol = 2)
mat.r18.2000g <- as.data.frame(mat.r18.2000g)
mat.r18.2000g$V1 <- speciesTree.order.3
a <- 1
for(i in 1:length(speciesTree.order.3)) {
  b <- speciesTree.order.3[a]
  cell.names <- r18.2000g.80dim.df$r18.2000g.80dim.cells[r18.2000g.80dim.df$r18.2000g.80dim.clusters==b]
  cell.names <- paste(cell.names, collapse = ", ")
  mat.r18.2000g[i,2] <- cell.names
  a <- a + 1
}

mat.r18.3000g <- matrix(nrow = length(speciesTree.order.4), ncol = 2)
mat.r18.3000g <- as.data.frame(mat.r18.3000g)
mat.r18.3000g$V1 <- speciesTree.order.4
a <- 1
for(i in 1:length(speciesTree.order.4)) {
  b <- speciesTree.order.4[a]
  cell.names <- r18.3000g.80dim.df$r18.3000g.80dim.cells[r18.3000g.80dim.df$r18.3000g.80dim.clusters==b]
  cell.names <- paste(cell.names, collapse = ", ")
  mat.r18.3000g[i,2] <- cell.names
  a <- a + 1
}

write.table(mat.r18.500g, file = "r18_500g.txt", row.names = FALSE, sep = "\t", col.names = FALSE, quote = FALSE, eol = "\r")
write.table(mat.r18.1000g, file = "r18_1000g.txt", row.names = FALSE, sep = "\t", col.names = FALSE, quote = FALSE, eol = "\r")
write.table(mat.r18.2000g, file = "r18_2000g.txt", row.names = FALSE, sep = "\t", col.names = FALSE, quote = FALSE, eol = "\r")
write.table(mat.r18.3000g, file = "r18_3000g.txt", row.names = FALSE, sep = "\t", col.names = FALSE, quote = FALSE, eol = "\r")
```


# Different approach: use identities from one object (80 dims, 2000 hvg) and plot them in the query umap

```{r}
# using cluster ordering g to dendrogram order of r18.2000g.80dim
mycols.tree.names <- c("6", "49", "8", "11", "19", "7", "23", "20", "16", 
                       "21", "32", "62", "55", "10", "33", "2", "15", "31", 
                       "3", "13", "24", "56", "1", "22", "58", "17", "30", 
                       "64", "45", "5", "9", "27", "61", "52", "12", "40", 
                       "14", "54", "39", "37", "44", "57", "4", "26", "38", 
                       "65", "25", "59", "51", "28", "47", "48", "36", "41", 
                       "53", "18", "43", "46", "29", "34", "42", "63", "35", 
                       "50", "60")
colors.tree <- hue_pal()(65)

names(colors.tree) <- mycols.tree.names
```

```{r fig.height=10, fig.width=20}
r18.2000g.80dim.cells.id <- Idents(r18.2000g.80dim) # SLM_idents_2.1

r18.500g.80dim[["Obj_2000hvg_idents"]] <- r18.2000g.80dim.cells.id
p1 <- DimPlot(int, label = TRUE, pt.size = 2, label.size = 6, cols = colors.tree) + NoLegend()
p2 <- DimPlot(r18.500g.80dim, label = TRUE, pt.size = 2, label.size = 6, group.by = "Obj_2000hvg_idents", cols = colors.tree) + NoLegend()

r18.1000g.80dim[["Obj_2000hvg_idents"]] <- r18.2000g.80dim.cells.id
p3 <- DimPlot(int, label = TRUE, pt.size = 2, label.size = 6, cols = colors.tree) + NoLegend()
p4 <- DimPlot(r18.1000g.80dim, label = TRUE, pt.size = 2, label.size = 6, group.by = "Obj_2000hvg_idents", cols = colors.tree) + NoLegend()

r18.3000g.80dim[["Obj_2000hvg_idents"]] <- r18.2000g.80dim.cells.id
p5 <- DimPlot(int, label = TRUE, pt.size = 2, label.size = 6) + NoLegend()
p6 <- DimPlot(r18.3000g.80dim, label = TRUE, pt.size = 2, label.size = 6, group.by = "Obj_2000hvg_idents", cols = colors.tree) + NoLegend()

p1+p2
p3+p4
p5+p6
```

# PDFs

```{r}
pdf("DimPlot_int_rep500g_by2000hvg.pdf", width = 10, height = 10)
DimPlot(r18.500g.80dim, reduction = 'umap', label = T, raster = FALSE, pt.size = 0.8, label.size = 3, group.by = "Obj_2000hvg_idents") + NoLegend()
dev.off()

pdf("DimPlot_int_rep1000g_by2000hvg.pdf", width = 10, height = 10)
DimPlot(r18.1000g.80dim, reduction = 'umap', label = T, raster = FALSE, pt.size = 0.8, label.size = 3, group.by = "Obj_2000hvg_idents", cols = mycols.1) + NoLegend()
dev.off()

pdf("DimPlot_int_rep3000g_by2000hvg.pdf", width = 10, height = 10)
DimPlot(r18.3000g.80dim, reduction = 'umap', label = T, raster = FALSE, pt.size = 0.8, label.size = 3, group.by = "Obj_2000hvg_idents") + NoLegend()
dev.off()
```

```{r}
pdf("DimPlot_int_rep500g.pdf", width = 10, height = 10)
DimPlot(r18.500g.80dim, reduction = 'umap', label = T, raster = FALSE, pt.size = 0.8, label.size = 3) + NoLegend()
dev.off()

pdf("DimPlot_int_rep1000g.pdf", width = 10, height = 10)
DimPlot(r18.1000g.80dim, reduction = 'umap', label = T, raster = FALSE, pt.size = 0.8, label.size = 3) + NoLegend()
dev.off()

pdf("DimPlot_int_rep2000g.pdf", width = 10, height = 10)
DimPlot(r18.2000g.80dim, reduction = 'umap', label = T, raster = FALSE, pt.size = 0.8, label.size = 3, cols = c('1' = "#F8766D")) + NoLegend()
dev.off()

pdf("DimPlot_int_rep3000g.pdf", width = 10, height = 10)
DimPlot(r18.3000g.80dim, reduction = 'umap', label = T, raster = FALSE, pt.size = 0.8, label.size = 3) + NoLegend()
dev.off()
```

# PNGs

```{r}
png("DimPlot_int_rep500g_by2000hvg_rainbow.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.500g.80dim, reduction = 'umap', label = F, raster = FALSE, pt.size = 0.8, group.by = "Obj_2000hvg_idents", cols = colors.tree) + NoLegend()
dev.off()

png("DimPlot_int_rep1000g_by2000hvg_rainbow.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.1000g.80dim, reduction = 'umap', label = F, raster = FALSE, pt.size = 0.8, group.by = "Obj_2000hvg_idents", cols = colors.tree) + NoLegend()
dev.off()

png("DimPlot_int_rep3000g_by2000hvg_rainbow.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.3000g.80dim, reduction = 'umap', label = F, raster = FALSE, pt.size = 0.8, group.by = "Obj_2000hvg_idents", cols = colors.tree) + NoLegend()
dev.off()
```

```{r}
png("DimPlot_int_rep500g_grey.png", width = 10, height = 10, units = 'in', res = 400)
DimPlot(r18.500g.80dim, reduction = 'umap', label = F, raster = FALSE, pt.size = 0.8, cols = rep('darkgrey', length(levels(r18.500g.80dim)))) + NoLegend()
dev.off()

png("DimPlot_int_rep1000g_grey.png", width = 10, height = 10, units = 'in', res = 400)
DimPlot(r18.1000g.80dim, reduction = 'umap', label = F, raster = FALSE, pt.size = 0.8, cols = rep('darkgrey', length(levels(r18.1000g.80dim)))) + NoLegend()
dev.off()

png("DimPlot_int_rep2000g_grey.png", width = 10, height = 10, units = 'in', res = 400)
DimPlot(r18.2000g.80dim, reduction = 'umap', label = F, raster = FALSE, pt.size = 0.8, cols = rep('darkgrey', length(levels(r18.2000g.80dim)))) + NoLegend()
dev.off()

png("DimPlot_int_rep3000g_grey.png", width = 10, height = 10, units = 'in', res = 400)
DimPlot(r18.3000g.80dim, reduction = 'umap', label = F, raster = FALSE, pt.size = 0.8, cols = rep('darkgrey', length(levels(r18.3000g.80dim)))) + NoLegend()
dev.off()
```

# Plots by species

```{r}
species_annot <- r18.500g.80dim@meta.data$species
names(species_annot) <- rownames(r18.500g.80dim@meta.data)
lizard.id.1 <- names(species_annot[species_annot == "lizard"])
turtle.id.1 <- names(species_annot[species_annot == "turtle"])
salama.id.1 <- names(species_annot[species_annot == "salamander"])

species_annot <- r18.1000g.80dim@meta.data$species
names(species_annot) <- rownames(r18.1000g.80dim@meta.data)
lizard.id.2 <- names(species_annot[species_annot == "lizard"])
turtle.id.2 <- names(species_annot[species_annot == "turtle"])
salama.id.2 <- names(species_annot[species_annot == "salamander"])

species_annot <- r18.2000g.80dim@meta.data$species
names(species_annot) <- rownames(r18.2000g.80dim@meta.data)
lizard.id.3 <- names(species_annot[species_annot == "lizard"])
turtle.id.3 <- names(species_annot[species_annot == "turtle"])
salama.id.3 <- names(species_annot[species_annot == "salamander"])

species_annot <- r18.3000g.80dim@meta.data$species
names(species_annot) <- rownames(r18.3000g.80dim@meta.data)
lizard.id.4 <- names(species_annot[species_annot == "lizard"])
turtle.id.4 <- names(species_annot[species_annot == "turtle"])
salama.id.4 <- names(species_annot[species_annot == "salamander"])

png("DimPlot_int_rep500g_byspecies_salamander.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.500g.80dim, reduction = 'umap', label = F, raster = FALSE, sizes.highlight = 0.3, cols.highlight = "black", na.value = "darkgrey", pt.size = 0.8, cells.highlight = salama.id.1) + NoLegend()
dev.off()

png("DimPlot_int_rep1000g_byspecies_salamander.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.1000g.80dim, reduction = 'umap', label = F, raster = FALSE, sizes.highlight = 0.3, cols.highlight = "black", na.value = "darkgrey", pt.size = 0.8, cells.highlight = salama.id.2) + NoLegend()
dev.off()

png("DimPlot_int_rep2000g_byspecies_salamander.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.2000g.80dim, reduction = 'umap', label = F, raster = FALSE, sizes.highlight = 0.3, cols.highlight = "black", na.value = "darkgrey", pt.size = 0.8, cells.highlight = salama.id.3) + NoLegend()
dev.off()

png("DimPlot_int_rep3000g_byspecies_salamander.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.3000g.80dim, reduction = 'umap', label = F, raster = FALSE, sizes.highlight = 0.3, cols.highlight = "black", na.value = "darkgrey", pt.size = 0.8, cells.highlight = salama.id.4) + NoLegend()
dev.off()

png("DimPlot_int_rep500g_byspecies_turtle.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.500g.80dim, reduction = 'umap', label = F, raster = FALSE, sizes.highlight = 0.3, cols.highlight = "black", na.value = "darkgrey", pt.size = 0.8, cells.highlight = turtle.id.1) + NoLegend()
dev.off()

png("DimPlot_int_rep1000g_byspecies_turtle.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.1000g.80dim, reduction = 'umap', label = F, raster = FALSE, sizes.highlight = 0.3, cols.highlight = "black", na.value = "darkgrey", pt.size = 0.8, cells.highlight = turtle.id.2) + NoLegend()
dev.off()

png("DimPlot_int_rep2000g_byspecies_turtle.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.2000g.80dim, reduction = 'umap', label = F, raster = FALSE, sizes.highlight = 0.3, cols.highlight = "black", na.value = "darkgrey", pt.size = 0.8, cells.highlight = turtle.id.3) + NoLegend()
dev.off()

png("DimPlot_int_rep3000g_byspecies_turtle.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.3000g.80dim, reduction = 'umap', label = F, raster = FALSE, sizes.highlight = 0.3, cols.highlight = "black", na.value = "darkgrey", pt.size = 0.86, cells.highlight = turtle.id.4) + NoLegend()
dev.off()

png("DimPlot_int_rep500g_byspecies_lizard.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.500g.80dim, reduction = 'umap', label = F, raster = FALSE, sizes.highlight = 0.3, cols.highlight = "black", na.value = "darkgrey", pt.size = 0.8, cells.highlight = lizard.id.1) + NoLegend()
dev.off()

png("DimPlot_int_rep1000g_byspecies_lizard.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.1000g.80dim, reduction = 'umap', label = F, raster = FALSE, sizes.highlight = 0.3, cols.highlight = "black", na.value = "darkgrey", pt.size = 0.8, cells.highlight = lizard.id.2) + NoLegend()
dev.off()

png("DimPlot_int_rep2000g_byspecies_lizard.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.2000g.80dim, reduction = 'umap', label = F, raster = FALSE, sizes.highlight = 0.3, cols.highlight = "black", na.value = "darkgrey", pt.size = 0.8, cells.highlight = lizard.id.3) + NoLegend()
dev.off()

png("DimPlot_int_rep3000g_byspecies_lizard.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.3000g.80dim, reduction = 'umap', label = F, raster = FALSE, sizes.highlight = 0.3, cols.highlight = "black", na.value = "darkgrey", pt.size = 0.88, cells.highlight = lizard.id.4) + NoLegend()
dev.off()

# grouped by species
mycols <- c("#EECC66", "#EE99AA", "#6699CC")

png("DimPlot_int_rep500g_byspecies_grouped.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.500g.80dim, reduction = 'umap', label = F, shuffle = TRUE, pt.size = 0.8, group.by = "species", cols = mycols) + NoLegend()
dev.off()

png("DimPlot_int_rep1000g_byspecies_gropuped.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.1000g.80dim, reduction = 'umap', label = F, shuffle = TRUE, pt.size = 0.8, group.by = "species", cols = mycols) + NoLegend()
dev.off()

png("DimPlot_int_rep2000g_byspecies_grouped.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.2000g.80dim, reduction = 'umap', label = F, shuffle = TRUE, pt.size = 0.8, group.by = "species", cols = mycols) + NoLegend()
dev.off()

png("DimPlot_int_rep3000g_byspecies_grouped.png", width = 10, height = 10, units = 'in', res = 800)
DimPlot(r18.3000g.80dim, reduction = 'umap', label = F, shuffle = TRUE, pt.size = 0.8, group.by = "species", cols = mycols) + NoLegend()
dev.off()
```




